
steps:
  build:
    image: alpine
    commands:
      - apk add --no-cache $SCHEME make rsync git wget
      - make build
      - CI=1 make test
    when:
      branch: [master, development]

matrix:
  SCHEME:
    - guile
