
name: Makefile CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  schedule:
    - cron: '0 14 * * 2'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        scheme: [guile-3.0]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.scheme }} git python3-sphinx docker docker-compose docker.io docker-registry containerd swi-prolog
    - name: Run build
      run: make build
    - name: Run test
      run: CI=1 make test
